### ---------------------------------------------------------------------------
### --- Project: QURATOR Curious Facts (QCF)
### --- Version 1.0.0
### --- December 2021.
### --- Author: Goran S. Milovanovic, Data Scientist, WMDE
### --- Developed under the contract between Goran Milovanovic PR Data Kolektiv
### --- and WMDE.
### --- Description: data update for the Qurator Curious Facts system
### --- Contact: goran.milovanovic_ext@wikimedia.de
### ---------------------------------------------------------------------------

version: "3.0"

services:
  quratorqcf:
    container_name: quratorqcfrevolver
    # To build the image locally, comment out "image" below, and uncomment
    # "build" and the lines indented under it.
    image: quratorqcfrevolver-img
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    user: 'root'
    volumes: 
      - /srv/_data/curiousfacts_data:/app/data